# Pandas----> panel data
- data representation in Pandas is better than numpy
- we can even store hetrogenous data

In [ ]:
# library

In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\lenovo\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas) (2.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
# importing
import pandas as pd

In [8]:
import numpy as np

In [15]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
pd.__version__

'2.3.3'

In [ ]:
# datastructures in Pandas
1d ---> Series
2D ---> Data Frame

# Series
- it is the 1D data in Pandas

In [ ]:
Creating series
- list
- dict
- array

In [4]:
# list
rivers = ["Cauvery" , "Ganga" , "Yamuna" , "Narmada"  , "Godaveri"]

In [5]:
type(rivers
    )

list

In [6]:
rivers_se = pd.Series(rivers)
rivers_se

0     Cauvery
1       Ganga
2      Yamuna
3     Narmada
4    Godaveri
dtype: object

In [7]:
type(rivers_se)

pandas.core.series.Series

In [10]:
random_array = np.random.rand(5)
random_array

array([0.09234714, 0.10010737, 0.28267396, 0.09259117, 0.65697173])

In [11]:
random_ser = pd.Series(random_array)
random_ser

0    0.092347
1    0.100107
2    0.282674
3    0.092591
4    0.656972
dtype: float64

In [ ]:
# index and slicing
both on index numbers  , given index values

In [27]:
rivers_se = pd.Series(rivers , index=["a","b" , "c" , "d" , "e"])
rivers_se

a     Cauvery
b       Ganga
c      Yamuna
d     Narmada
e    Godaveri
dtype: object

In [16]:
# by index
rivers_se[3]

'Narmada'

In [17]:
# by given index value
rivers_se["d"]

'Narmada'

In [29]:
# by index
rivers_se[0:3:]

a    Cauvery
b      Ganga
c     Yamuna
dtype: object

In [30]:
rivers_se

a     Cauvery
b       Ganga
c      Yamuna
d     Narmada
e    Godaveri
dtype: object

In [32]:
# by given index value
rivers_se["a":"c":]

a    Cauvery
b      Ganga
c     Yamuna
dtype: object

In [38]:
d = {"first":"Alex" , "Second":"Laura"}

In [39]:
d

{'first': 'Alex', 'Second': 'Laura'}

In [41]:
pd.Series(d)

first      Alex
Second    Laura
dtype: object

# Data Frame
- it is a 2D structure of Pandas

# Creating a data frame

# 1 loading a file as DataFrame

In [42]:
pwd

'C:\\Users\\Lenovo\\Desktop\\16 Feb'

In [43]:
ls

 Volume in drive C has no label.
 Volume Serial Number is 6CE9-051B

 Directory of C:\Users\Lenovo\Desktop\16 Feb

26-03-2026  21:05    <DIR>          .
26-03-2026  21:05    <DIR>          ..
26-03-2026  20:21    <DIR>          .ipynb_checkpoints
16-03-2026  21:21    <DIR>          __pycache__
17-03-2026  22:41               109 abc.txt
03-03-2026  20:12             1,610 Class1_anaconda_installation.ipynb
03-03-2026  22:40            40,281 class10_list_comp_exercises.ipynb
05-03-2026  22:22            67,066 Class11_tuple_dict.ipynb
09-03-2026  22:33           110,932 Class12_dict_methods_set_Conditional_statements.ipynb
10-03-2026  22:42            44,586 Class13_loops.ipynb
11-03-2026  22:43         4,320,470 Class14_Functions.ipynb
17-03-2026  22:45            59,593 Class15_Functions_2.ipynb
16-03-2026  22:28           111,056 Class16_function_3_modules_FileHandling.ipynb
17-03-2026  22:42            64,164 Class17_File_Handling_2.ipynb
23-03-2026  20:22            71,867 Class18_Exception_Handling_Regex_1.ipynb
23-03-2026  22:33           539,025 Class19_Regex_2.ipynb
17-02-2026  22:40            22,550 Class2_Intro_to_Python.ipynb
18-02-2026  22:43            46,599 Class3_Python_Components.ipynb
19-02-2026  22:29           574,793 Class4_Operations_in_Python.ipynb
23-02-2026  22:39            68,907 Class5_float_complex_bool_None_str.ipynb
25-02-2026  21:46           515,873 Class6_f_str_str_properties_indexing_Slicing.ipynb
26-02-2026  20:28            52,218 Class7_str_operation_methods.ipynb
02-03-2026  20:23            63,371 Class8_Str_methods_Sequence_ch_list.ipynb
03-03-2026  20:51            83,474 Class9_list_list_methods.ipynb
26-03-2026  21:03    <DIR>          datasets
24-02-2026  20:24           291,571 image.png
25-03-2026  21:58            41,191 iron man.jpg
17-03-2026  21:06                 0 my_file.txt
16-03-2026  21:29               602 my_module.py
24-03-2026  22:44           188,099 Numpy_Class_1.ipynb
25-03-2026  22:39         2,674,918 Numpy_Class_2.ipynb
26-03-2026  21:05            74,812 Pandas_Class_1.ipynb
              27 File(s)     10,129,737 bytes
               5 Dir(s)  48,130,662,400 bytes free

In [ ]:
syntax
pd.read_csv("path/file_name.csv")

In [49]:
# df = pd.read_csv(r"C:/UsersLenovo/Desktop/16 Feb/datasets/ted_data.csv")
df = pd.read_csv(r"C:\Users\Lenovo\Desktop\16 Feb\datasets\ted_data.csv")

In [50]:
df

,name_speaker,speaker_occupation,title,views,comments
0,Ken Robinson,Author/educator,Do schools kill creativity?,47227110,4553
1,Al Gore,Climate advocate,Averting the climate crisis,3200520,265
2,David Pogue,Technology columnist,Simplicity sells,1636292,124
3,Majora Carter,Activist for environmental justice,Greening the ghetto,1697550,200
4,Hans Rosling,Global health expert; data visionary,The best stats you've ever seen,12005869,593
5,Tony Robbins,Life coach; expert in leadership psychology,Why we do what we do,20685401,672
6,Julia Sweeney,"Actor, comedian, playwright",Letting go of God,3769987,919
7,Joshua Prince-Ramus,Architect,Behind the design of Seattle's library,967741,46
8,Dan Dennett,"Philosopher, cognitive scientist",Let's teach religion -- all religion -- in sch...,2567958,582
9,Rick Warren,"Pastor, author",A life of purpose,3095993,900

In [51]:
# df = pd.read_csv(r"C:/UsersLenovo/Desktop/16 Feb/datasets/ted_data.csv")
df = pd.read_csv(r"datasets\ted_data.csv")

In [52]:
df

,name_speaker,speaker_occupation,title,views,comments
0,Ken Robinson,Author/educator,Do schools kill creativity?,47227110,4553
1,Al Gore,Climate advocate,Averting the climate crisis,3200520,265
2,David Pogue,Technology columnist,Simplicity sells,1636292,124
3,Majora Carter,Activist for environmental justice,Greening the ghetto,1697550,200
4,Hans Rosling,Global health expert; data visionary,The best stats you've ever seen,12005869,593
5,Tony Robbins,Life coach; expert in leadership psychology,Why we do what we do,20685401,672
6,Julia Sweeney,"Actor, comedian, playwright",Letting go of God,3769987,919
7,Joshua Prince-Ramus,Architect,Behind the design of Seattle's library,967741,46
8,Dan Dennett,"Philosopher, cognitive scientist",Let's teach religion -- all religion -- in sch...,2567958,582
9,Rick Warren,"Pastor, author",A life of purpose,3095993,900

In [ ]:
^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

In [53]:
# reading excel file
df_e = pd.read_excel(r"datasets/football_worldcup.xlsx")

ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.

In [ ]:
xlrd

In [54]:
!pip install xlrd

Requirement already satisfied: xlrd in c:\users\lenovo\anaconda3\lib\site-packages (2.0.1)

In [56]:
# reading excel file
df_e = pd.read_excel(r"datasets\football_worldcup.xlsx")

ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.

In [57]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [61]:
# reading excel file
df_e = pd.read_excel(r"datasets\football_worldcup.xlsx" )

In [59]:
df_e

   Year       Country    Winner   Runners-Up  GoalsScored  MatchesPlayed
0  1990         Italy  Germany     Argentina          115             52
1  1994           USA    Brazil        Italy          141             52
2  1998        France    France       Brazil          171             64
3  2002         Japan    Brazil      Germany          161             64
4  2006       Germany     Italy       France          147             64
5  2010  South Africa     Spain  Netherlands          145             64
6  2014        Brazil   Germany    Argentina          171             64

# 2 Creating DF using a dict

In [62]:
d = {"year":[1990, 1994,1998,2002],
    "country":["Italy" , "USA" , "France" , "Japan"],
    "winner":["Germany" , "Brazil" , "France" , "India"],
    }

In [63]:
d

{'year': [1990, 1994, 1998, 2002],
 'country': ['Italy', 'USA', 'France', 'Japan'],
 'winner': ['Germany', 'Brazil', 'France', 'India']}

In [64]:
pd.DataFrame(d)

   year country   winner
0  1990   Italy  Germany
1  1994     USA   Brazil
2  1998  France   France
3  2002   Japan    India

In [65]:
# Creating DF using a Series
my_d = {"year":[1990, 1994,1998,2002,2004],
    "country":["Italy" , "USA" , "France" , "Japan"],
    "winner":["Germany" , "Brazil" , "France" , "India"],
    }

In [66]:
my_d

{'year': [1990, 1994, 1998, 2002, 2004],
 'country': ['Italy', 'USA', 'France', 'Japan'],
 'winner': ['Germany', 'Brazil', 'France', 'India']}

In [68]:
pd.DataFrame(my_d)

ValueError: All arrays must be of the same length

In [69]:
my_d = {"year":pd.Series([1990, 1994,1998,2002,2004]),
    "country":pd.Series(["Italy" , "USA" , "France" , "Japan"]),
    "winner":pd.Series(["Germany" , "Brazil" , "France" , "India"]),
    }

In [70]:
pd.DataFrame(my_d)

   year country   winner
0  1990   Italy  Germany
1  1994     USA   Brazil
2  1998  France   France
3  2002   Japan    India
4  2004     NaN      NaN

In [ ]:
Not a Number ---> None

In [ ]:
lst =[a , b , c]

In [ ]:
LOt ---> list of tuples

In [ ]:
nested list

In [71]:
lot = [(2002  , "China" , "India" , 7),
        (2004  , "Russia" , "USA" , 3)]

In [72]:
lot

[(2002, 'China', 'India', 7), (2004, 'Russia', 'USA', 3)]

In [73]:
pd.DataFrame(lot)

      0       1      2  3
0  2002   China  India  7
1  2004  Russia    USA  3

In [74]:
pd.DataFrame(lot , columns=["year" , "Host" , "Winner" , "goals"])

   year    Host Winner  goals
0  2002   China  India      7
1  2004  Russia    USA      3

In [ ]:
Naukri
Shine.com
Indeed
FoundIT
LinkedIn

InternShala

In [ ]:
API 
Flask
Streamlit
Django
DSA System Desi